---
title: "Tiago's resume"
author: Tiago Cabaço
date: "`r Sys.Date()`"
output:
  pagedown::html_resume:
    # set it to true for a self-contained HTML page but it'll take longer to render
    self_contained: false
# uncomment this line to produce HTML and PDF in RStudio:
knit: pagedown::chrome_print
---

Aside
================================================================================


Contact Info {#contact}
--------------------------------------------------------------------------------

- <i class="fa fa-envelope"></i> tiago.joao.cabaco@gmail.com
- <i class="fa fa-github"></i> [github.com/tijoalca](https://github.com/tijoalca)
- <i class="fa fa-phone"></i> +49 176 439 822 51



Skills {#skills}
--------------------------------------------------------------------------------

- Statistical analysis
- Bayesian inference
- Probabilistic programming
- Data cleaning and pre-processing
- Data visualization 
- Teaching
- Public speaking


Programming languages {#skills}
--------------------------------------------------------------------------------

- Highly skilled in R, Stan and LaTeX

- Skilled in Bash

- Familiar with Python and C++


Tools {#skills}
--------------------------------------------------------------------------------

- git 
- R markdown reports

Languages {#skills}
--------------------------------------------------------------------------------

- English (Fluent)
- Portuguese (Native)
- German (A1)


Main
================================================================================

Tiago Cabaço {#title}
--------------------------------------------------------------------------------


Professional Experience {data-icon=laptop}
--------------------------------------------------------------------------------

### Doctoral Research Fellow

Humboldt-University 

Berlin

Today - 2016
  
- Work with a large data set (> 4.000.000 data points) and developed techniques for data pre-processing and quality assessment using R.   
- Build computational models of decision making using probabilistic programming language Stan.
- Developed extensive experience with hierarchical Bayesian regression techniques with a focus on scalable solutions.
- Strong use of visualizations using R to communicate insights and assess statistical model performance. 

### Research Trainee  

Psychological methods group

University of Amsterdam, NL

2015 - 2016

- Created, maintained and fact-checked an archival data base with historical events from the Psychometric Society. 
- Used R to develop and deploy animated network visualizations of sequences of events. 
- My work resulted in a publication and in a positive traineeship evaluation.

### Telemarketer

Yourvoice Contact Solutions lda

Lisbon, Portugal

2015 - 2014

- Acquired a goal-orientation attitude and skills needed to work in a fast-paced and high pressure role, as demonstrated by being in the 'Top 5' employees for successive months.

### Psychologist, intern

Center for Family  and Parental Support

Barreiro, Portugal

2014 - 2013

- Developed inter-disciplinary team work and project management skills by conducting youth group interventions, organizing community events and family counseling activities. 


### Research Consultant 

Freelance

Lisbon, Portugal

2014 - 2012

- Consulted several research projects by supporting data analysis projects, and by conducting and translating structured interviews.


### Librarian

Library of Psychology, University of Lisbon

Lisbon, Portugal

2013 - 2012 

- Learned excellent communication and organizational skills, by being responsible for costumer care and for organizing the reading space and storage repositories.


### Research Assistant 

Cognitive psychology lab

University of Lisbon, Portugal

2012 - 2011

- Assisted ongoing research projects by doing data collection and literature review, resulting in an authored publication and development of project management skills.


### Research Fellow

Grant by Amadeu Dias Foundation

Lisbon, Portugal

2011 - 2010

- Responsible for data collection, lab management and reporting. The project received the Foundation's award for best social sciences project.



Education {data-icon=graduation-cap}
--------------------------------------------------------------------------------

### PhD in Computational Psychology

Humboldt-University 

Berlin

Today - 2016

- Grant by the International Max Planck Research School on the Life Course.


### Erasmus Intensive Program in Mathematical Psychology

University of Tartu

Sagadi, Estonia

2014


### Masters in Clinical Psychology

University of Lisbon

Lisbon, Portugal

2015 - 2012

For my thesis I developed and deployed an online survey, and self-learned R to implement a non-standard statistical model. All of which resulted in receiving the highest grade possible.  


### BA in Psychological Sciences

University of Lisbon

Lisbon, Portugal

2011 - 2009




Publications {data-icon=file}
--------------------------------------------------------------------------------

- Wijsen, L. D., Borsboom, D.,  **Cabaço, T.**, & Heiser, W. J. (2019).  *An Academic Genealogy of Psychometric Society Presidents*. *Psychometrika*, *84*(2), 562-588.
- Almeida, J., Mahon, B. Z., Zapater-Raberov, V., Dziuba, A., **Cabaço, T.**, Marques, J. F., & Caramazza, A. (2014). Grasping with the eyes: *The role of elongation in visual recognition of manipulable objects. Cognitive, Affective, & Behavioral Neuroscience*, *14*(1), 319-335.