---
title: "Tiago's resume"
author: Tiago Cabaço
date: "`r Sys.Date()`"
output:
    pagedown::html_resume:
    # set it to true for a self-contained HTML page but it'll take longer to render
        css: custom_resume.css
    self_contained: false
# uncomment this line to produce HTML and PDF in RStudio:
knit: pagedown::chrome_print
---

Aside
================================================================================

Contact Info {#contact}
--------------------------------------------------------------------------------

- <i class="fa fa-envelope"></i> tcabaco@pm.me
- <i class="fa fa-phone"></i>  +49 176 439 822 51
- <i class="fa fa-github"></i> [github.com/tau31](https://github.com/)

Skills {#skills}
--------------------------------------------------------------------------------

- - Troubleshooting and Problem-solving

- - Adaptability and Quick Learning

- - Effective communication of complex analytical concepts, including public speaking

- - Statistical analysis and reporting

Tools {#skills}
--------------------------------------------------------------------------------

- <span style="font-size:10pt">**Operating Systems**</span>

- MacOS
- Linux (Ubuntu, Debian, FreeBSD)
- Windows 10/11

- <span style="font-size:10pt">**Programming Languages**</span>

- R, Python, SQL, Bash

- <span style="font-size:10pt">**Software tools**</span>

- Issue Tracking with Jira
- Dynamic Reporting with Quarto
- Version  Control with git

- <span style="font-size:10pt">**Languages**</span>

- English (Fluent)
- Portuguese (Native)
- German (A2, planning to take B1 exam in January 2025)

Main 
================================================================================

Tiago Cabaço {#title}
--------------------------------------------------------------------------------
I am a Psychologist, with Data Science and Software Development experience, 
looking to start my career in IT.

Currently, I am searching for entry-level IT support roles. 

<!-- ### About me -->
<!-- I hold a Master degree in Psychology and I am a Data Scientist that uses tools like R, SQL, Python and Bash. -->

<!-- I enjoy the challenges of processing and exploring complex data, and I use statistics to  -->
<!-- uncover findings and insights. -->

<!-- I welcome the collaboration with colleagues and I am very driven to adjust to each audience when communicating -->
<!-- findings and results. -->

<!-- Being able to dive deep into new topics and learn new technologies, is something that is very dear to me.  -->

<!-- I am looking for an opportunity where I can use my skills to make a difference in people's life and in our society. -->

Certifications {data-icon=computer}
--------------------------------------------------------------------------------

### CompTIA A+

[comptia.org/certifications/a](https://www.comptia.org/certifications/a#overview)

Remote 

Expected on 22/11/2024

- Learning essential IT skills required for supporting and troubleshooting:
   - Hardware;
    - Software;
    - Mobile devices;
    - Networking;
    - Operating Systems;
    - Virtualization and Cloud Computing;
    - Security.

- Requires completion of two exams:
    - Core 1: completed on 06/08/2024
    - Core 2: scheduled for 22/11/2024

Experience {data-icon=briefcase}
--------------------------------------------------------------------------------

### Senior R Developer / Data Scientist

[Civey](https://civey.com/) 

Berlin, DE

October 2023 - August 2022

- Developed software to perform statistical analysis of survey data from millions of users using R, Python, SQL and Bash.
<!-- - Performed and presented analytical reports, using product and user behavior data, to stakeholders.  -->
- Coordinated the performance monitoring of our software products, including reporting and addressing troubleshooting requests
from other teams. 
- Configured and troubleshooted other team's systems (Linux and MacOS) to use our software products.
- Created and extended company-wide documentation on my team's statistical and software products. 
- Trained new team members by using documentation, learning sessions, joint code reviews and 
pair-programming.


<!-- - Developed R statistical libraries used daily to transform millions of user's survey responses 
into statistically representative results, used on all the company's costumer-facing products. 
- Analyzed data from millions of users using R, PostgreSQL and Clickhouse and produced visualizations, 
dashboards and reports to answer stakeholder's analytical requests, resulting in a better support for decisions 
across our products.
- Contributed to an extensive refactoring of a core functionality which
simplified its maintenance and improved its extendibility, culminating in the development of a new
product. 
- Coordinated the monitoring of our R software products, including the cooperation with 
other teams, which resulted in the development of new monitoring features and dashboards (e.g. Slack bots or 
Redash Dashboards) and in an improved communication and efficiency in problem-solving. 
- Developed internal tools with R, Bash, PostgreSQL, Clickhouse and Python used to support other teams,
resulting in an increased speed and flexibility to meet customer's requests. 
- Created documentation covering the statistical concepts and logic used in our products, which resulted in the 
improved understanding of our products, both internally and by other teams.  -->

### R Developer / Data Scientist

[Civey](https://civey.com/) 

Berlin, DE

2022 - 2020

- Contributed to the development of statistical libraries for survey data analysis using R, SQL and Bash. 
- Supported the installation of software in other team's systems to use our software products. 
<!-- - Contributed to the development of a bash command line tool used to configure the development environment in production. -->

<!-- - Contributed to the development of R libraries used to calculate more then 10.000 representative survey 
results daily.  
- Lead the development of a new feature for geographical survey analysis, resulting in an new product. 
- Developed a service that daily updates statistical estimates of the German population using R and Python Airflow, 
which directly improved the quality of our poll results.  
- Contributed to the development of bash command line tool used to configure the R environment in production, resulting 
in efficient and safe workflow for new releases to production.    -->

### Doctoral Research Fellow

Humboldt-University 

Berlin, DE

2020 - 2016

<!-- - Grant by the International Max Planck Research School on the Life Course. -->
- Developed Bash scripts to use of high performance computing clusters and threading in order to improve computations speed and scale. 
<!-- - Use of high performance computing clusters and threading in order to provide scalable modeling solutions. -->
<!-- - Applied hierarchical Bayesian regression and mixture modeling techniques, using the Stan probabilistic programming language, to account for different aspects of how the data was structured and generated. -->
<!-- - Applied hierarchical Bayesian regression and mixture modeling techniques, using the Stan probabilistic programming language. -->
- Worked with large data (millions of observations), using R to program and perform automated quality checking and data manipulation routines.  
<!-- - Developed visualizations using ggplot in R to efficiently communicate insights and assess statistical model performance. -->

<!-- ### Research Trainee   -->

<!-- Psychological methods group -->

<!-- University of Amsterdam, NL -->

<!-- 2016 - 2015 -->

<!-- - Created, maintained an archival data base with historical events from the Psychometric Society, resulting in a publication.  -->
<!-- - Developed R based animated network visualizations of sequences of historical events.  -->


### Telemarketer

Yourvoice Contact Solutions lda

Lisbon, Portugal

2015 - 2014

- Talked with potential customers on the phone to sell or extend their TV cable products. 
- Acquired a goal-orientation attitude and skills needed to work in a fast-paced and high pressure role, as demonstrated by being in the 'Top 5' employees for successive months.

### Psychologist, intern

Center for Family and Parental Support

Barreiro, Portugal

2014 - 2013

- Worked as Family Psychologist, supporting Families with children and running at-risk youth group events. 
- Developed inter-disciplinary team work and project management skills by leading community events.

<!-- ### Research Consultant -->

<!-- Freelance -->

<!-- Lisbon, Portugal -->

<!-- 2014 - 2012 -->

<!-- - Consulted several research projects by supporting data analysis projects, and by conducting and translating structured interviews. -->


### Librarian

Library of Psychology, University of Lisbon

Lisbon, Portugal

2013 - 2012 

- Developed my communication and organizational skills, by being responsible for costumer service and for organizing storage repositories.


<!-- ### Research Assistant  -->

<!-- Cognitive psychology lab -->

<!-- University of Lisbon, Portugal -->

<!-- 2012 - 2011 -->

<!-- - Assisted ongoing research projects by doing data collection and literature review, resulting in an authored publication and development of project management skills. -->


<!-- ### Research Fellow -->

<!-- Grant by Amadeu Dias Foundation -->

<!-- Lisbon, Portugal -->

<!-- 2011 - 2010 -->

<!-- - Responsible for data collection, lab management and reporting. The project received the foundation's award for best social sciences project. -->



Education {data-icon=graduation-cap}
--------------------------------------------------------------------------------

### PhD in Computational Psychology

Humboldt-University

Berlin

2022 - 2016

- Grant by the International Max Planck Research School on the Life Course.
- [Incomplete - did not graduate.]{.underline}

<!-- ### Erasmus Intensive Program in Mathematical Psychology

University of Tartu

Sagadi, Estonia

2014 -->


### Masters in Clinical Psychology

University of Lisbon

Lisbon, Portugal

2015 - 2012

<!-- For my thesis I developed and deployed an online survey, and self-learned R to implement a non-standard statistical model. All of which resulted in receiving the highest grade with distinction.   -->


### BA in Psychological Sciences

University of Lisbon

Lisbon, Portugal

2011 - 2009


<!-- Civic participation {data-icon=hands-helping}
--------------------------------------------------------------------------------

### Student representation

Graduate students representative

Berlin

2018 - 2017

- Agilized the communication between administration and students. 


### Elder Care

Elderly Care Home

Lisbon, Portugal

2014 - 2013

Supported physiotherapy sessions with the elderly.


### Student representation
Pedagogical Counsel

Faculty of Psychology, University of Lisbon

2013 - 2009

- As student body representative, I made the connection between students and faculty. 
- I was responsible for scheduling the exams for all courses and represented the faculty in an external evaluation process.  -->

<!-- ### Disaster Relief -->

<!-- Faculty of Psychology -->

<!-- University of Lisbon, Portugal -->

<!-- 2010 -->

<!-- - Organized a Goods Collection Campaign to support Madeira's population, when it was affected by disaster floods in February 2010. -->


<!-- ### Drug Addiction and Homelessness -->

<!-- Teen Challenge -->

<!-- Lisbon, Portugal -->

<!-- 2009 - 2006 -->

<!-- - Volunteered at the food and syringes delivery team. Organized and conducted community activities for children and elderly people in a disadvantaged neighborhood. -->

<!-- 
Publications {data-icon=file}
--------------------------------------------------------------------------------

- Wijsen, L. D., Borsboom, D.,  **Cabaço, T.**, & Heiser, W. J. (2019).  *An Academic Genealogy of Psychometric Society Presidents*. *Psychometrika*, *84*(2), 562-588.
- Almeida, J., Mahon, B. Z., Zapater-Raberov, V., Dziuba, A., **Cabaço, T.**, Marques, J. F., & Caramazza, A. (2014). Grasping with the eyes: *The role of elongation in visual recognition of manipulable objects. Cognitive, Affective, & Behavioral Neuroscience*, *14*(1), 319-335. -->
